### ISSUE TITLE
Should we use the bug `type` to show status?

### ISSUE THREAD

**Issue by piatra** [k88hudson/bugzy#112]
I have a PR in progress  to read the `type` field 

Bugzy
<img width="497" alt="image" src="https://user-images.githubusercontent.com/810040/55862628-56a6a900-5b68-11e9-8bbc-8ff5cf007359.png">
Bugzilla
<img width="326" alt="image" src="https://user-images.githubusercontent.com/810040/55862680-75a53b00-5b68-11e9-8b00-2dd7ed8c928d.png">

Do we want to do this? cc @k88hudson

**Comment by k88hudson** [comment]
Yes we definitely do

**Comment by k88hudson** [comment]
@piatra did you have a PR for this
