### ISSUE TITLE
Read regressions flag from regressed_by field

### ISSUE THREAD

**Issue by punamdahiya** [k88hudson/bugzy#117]
With regressions and regressed_by fields support in bugzilla, we should mark a bug as regression only if regressed_by field has a value in it

https://bmo.readthedocs.io/en/latest/api/core/v1/bug.html#get-bug

**Comment by punamdahiya** [comment]
With landing of bug https://bugzilla.mozilla.org/show_bug.cgi?id=1534280, 'regression' keyword will be replaced by the new `is_regression` field

**Comment by punamdahiya** [comment]
List of keywords supported right now https://bugzilla.mozilla.org/rest/field/bug/keywords

**Comment by k88hudson** [comment]
Looks like this is blocked on that field being added

**Comment by punamdahiya** [comment]
is_regression field in BMO tracked here
https://bugzilla.mozilla.org/show_bug.cgi?id=1545258
