### ISSUE TITLE
A way to see P2 & P3s that are in "New Tab" component

### ISSUE THREAD

**Issue by jessilyndavis** [k88hudson/bugzy#149]
Use case:
I want to see all P2 and P3 bugs that aren't part of a meta bug.

We have this view in Triage for New Tab: http://as-bugzy.herokuapp.com/triage/pocket

But once it's prioritized as a P2/P3, and if I forgot to set the meta bug or if it doesn't have a natural fit for a meta bug, I can't currently see it in Bugzy to remember to retriage it at the beginning of the next sprint (or be able to find them quickly mid-sprint).

Maybe tweak: http://as-bugzy.herokuapp.com/other-in-release/pocket  to show P2s/P3s?

**Comment by punamdahiya** [comment]
@jessilyndavis we have http://as-bugzy.herokuapp.com/other-pocket that includes bugs in the New Tab Page component that are not blocked by a P1 meta bug. You can reach this view in bugzy by clicking Other... under Firefox 70 | New Tab
