### ISSUE TITLE
Possible to add in "Points" column to bugs?

### ISSUE THREAD

**Issue by jessilyndavis** [k88hudson/bugzy#153]
We're starting to experiment with scoping work by points and tracking how many points we're able to tackle per iteration and release. Can we add a "Points" column to the different views in Bugzy? (If it's hard to make the view change globally, let me know - we can get creative with one view to start (maybe the "current iteration" view?) just to see how it works.)

Bonus points if we can see how many total points are assigned to an iteration & person.

Not super high priority - but something that would be great for internal work planning.

**Comment by k88hudson** [comment]
Yep, this should be doable!

**Comment by k88hudson** [comment]
Closed by 938a6a933bb22747a28ca53382a721055f23c9fb
