### ISSUE TITLE
Add Product: Firefox, Component: Pocket to Triage & New Tab Bugzy views

### ISSUE THREAD

**Issue by jessilyndavis** [k88hudson/bugzy#159]
We need a way to triage and track bugs in the

Product:Firefox
Component: Pocket

with our other New Tab workflows in Bugzy.

Can we get this component added to:
http://as-bugzy.herokuapp.com/triage/pocket

and

http://as-bugzy.herokuapp.com/other-pocket

?

**Comment by k88hudson** [comment]
Fixed by 5af9848
