### ISSUE TITLE
make it easy to file a new bug for a feature

### ISSUE THREAD

**Issue by dmose** [k88hudson/bugzy#18]
While looking at a Bugzy feature page, I would find it convenient to have a "New Bug" link which prefills a Bugzilla "new bug" page with the correct product, component, and bug to block so that this new bug is tracked as part of the feature.

**Comment by k88hudson** [comment]
This was fixed by 0bca15075637f396c1e1b44e4df3894346bdd9c8 and is now live in production

**Comment by dmose** [comment]
W00t; thanks @k88hudson!
