### ISSUE TITLE
Add support for 'chore' tags

### ISSUE THREAD

**Issue by tspurway** [k88hudson/bugzy#28]
To indicate a chore, we are decorating bugzilla tickets with the `whiteboard` field set to `[chore]`

Let's change bugzy so this  is displayed as a bugzy tag.

**Comment by k88hudson** [comment]
This PR might be helpful for hints about how to do this https://github.com/k88hudson/bugzy/commit/f59b7357ac9e94f1615627d0274c15d7749b04af#diff-d8aacf6360be9e39c01e68eee615d809R20
