### ISSUE TITLE
Add new release-based feature sidebar / Feature List page

### ISSUE THREAD

**Issue by k88hudson** [k88hudson/bugzy#31]
This is just an idea to have only relevant features for the current iteration showing up in the sidebar. The Feature List view can show a list of all features for release planning purposes.

![bugzy-sidebar-feature-list-comp](https://user-images.githubusercontent.com/1455535/41934915-0453ba16-7956-11e8-972d-7307f0cdc999.png)

**Comment by jasonLaster** [comment]
wow - looks great.
