### ISSUE TITLE
Add tabs to feature view for Engineering / QA / Completed

### ISSUE THREAD

**Issue by k88hudson** [k88hudson/bugzy#96]
We need:

* Some UI for tabs on the feature view
* new routes for the feature view (e.g. `/feature/12345/engineering`, default route should be engineering)
* engineering view should have everything that is currently in feature view except for resolved bugs
* QA view should have anything that is resolved but not marked verified
* completed view should have resolved bugs

**Comment by punamdahiya** [comment]
Closing issue as fixed https://github.com/k88hudson/bugzy/commit/f8a9c5113fbe931ba16531fdc56265ad9665c9e6
